### PR TITLE
fwmp.html update accept my PR plees

### PR DESCRIPTION
**Pull request by appleflyerv3**

### CODE REVIEW

**Comment by kxtzownsu** [comment]
whats with these visual bugs
image

**Comment by kxtzownsu** [comment]
i think the text overlap in the top left is a result of me messing with gbb flaginator

**Comment by appleflyerv3** [comment]
random space fixed @kxtzownsu

**Comment by appleflyerv3** [comment]
title snap fixed

**Comment by kxtzownsu** [comment]
@appleflyerv3 can you add these flags to the JS (tested & working)

```
			const flagsDesc = {
				"FWMP_DEV_DISABLE_BOOT": "Disable developer mode. If this flag is set, booting the device in developer mode will take you straight to the TONORM screen, which asks you to confirm turning developer mode off.",
				"FWMP_DEV_DISABLE_RECOVERY": "Disable developer features of recovery images.",
				"FWMP_DEV_ENABLE_USB": "Enable Ctrl+U to boot from USB. Same effect as 'crossystem dev_boot_usb=1'.",
				"FWMP_DEV_ENABLE_LEGACY": "Enable Ctrl+L to boot from legacy OS. Same effect as 'crossystem dev_boot_legacy=1'.",
				"FWMP_DEV_ENABLE_OFFICIAL_ONLY": "Only accept developer images signed with the official Chrome OS key. Same effect as 'crossystem dev_boot_signed_only=1'.",
				"FWMP_DEV_USE_KEY_HASH": "Only accept developer images signed a specific key. If this is set, the SHA-256 digest of the kernel key data is compared with the digest stored in the FWMP. This enables you to decide what developer images will boot on your device, instead of blindly trusting them all. Particularly handy when combined with FWMP_DEV_ENABLE_USB.",
				"FWMP_DEV_DISABLE_CCD_UNLOCK": "Disables CCD Unlock",
				"FWMP_DEV_FIPS_MODE": "FIPS Mode"
			};
```

**Comment by appleflyerv3** [comment]
> @appleflyerv3 can you add these flags to the JS (tested & working)
> 
> ```
> 			const flagsDesc = {
> 				"FWMP_DEV_DISABLE_BOOT": "Disable developer mode. If this flag is set, booting the device in developer mode will take you straight to the TONORM screen, which asks you to confirm turning developer mode off.",
> 				"FWMP_DEV_DISABLE_RECOVERY": "Disable developer features of recovery images.",
> 				"FWMP_DEV_ENABLE_USB": "Enable Ctrl+U to boot from USB. Same effect as 'crossystem dev_boot_usb=1'.",
> 				"FWMP_DEV_ENABLE_LEGACY": "Enable Ctrl+L to boot from legacy OS. Same effect as 'crossystem dev_boot_legacy=1'.",
> 				"FWMP_DEV_ENABLE_OFFICIAL_ONLY": "Only accept developer images signed with the official Chrome OS key. Same effect as 'crossystem dev_boot_signed_only=1'.",
> 				"FWMP_DEV_USE_KEY_HASH": "Only accept developer images signed a specific key. If this is set, the SHA-256 digest of the kernel key data is compared with the digest stored in the FWMP. This enables you to decide what developer images will boot on your device, instead of blindly trusting them all. Particularly handy when combined with FWMP_DEV_ENABLE_USB.",
> 				"FWMP_DEV_DISABLE_CCD_UNLOCK": "Disables CCD Unlock",
> 				"FWMP_DEV_FIPS_MODE": "FIPS Mode"
> 			};
> ```

kk

**Comment by kxtzownsu** [comment]
looks good
thanks

**Pull request merged**
